name: Include Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
    - name: checkout
      run: |
        commits=${{ github.event.pull_request.commits }}
        if [[ -n "$commits" ]]; then
          # Prepare enough depth for diffs with master
          git fetch --depth="$(( commits + 1 ))"
        fi
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: runtime include analysis - check-dependency
      run: python3 ci/run_include_analysis.py --check-dependency
    - name: runtime include analysis - check-stability
      run: python3 ci/run_include_analysis.py --check-stability
