name: PyTorch Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Prepare PyTorch 1.8
      run: pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    - name: Echo GCC version
      run: gcc --version
    - name: Install MATXScript Requirements
      run: pip3 install -r python/requirements.txt
    - name: PyTorch Extension Test
      run: bash ci/run_py_extension_torch_test.sh
