name: Test Python Kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install requirements
        run: pip3 install msgpack && pip3 install numpy && pip3 install sympy
      - name: Add directory to PATH
        run: bash ./ci/download_mlir_binary.sh && echo "$GITHUB_WORKSPACE/mlir_build/pre_build/bin" >> $GITHUB_PATH
      - name: Test Python Script
        run: python3 ci/run_py_kernel_test.py
      
      - name: List directory on failure
        if: ${{ failure() }}
        run: ls -la "$GITHUB_WORKSPACE" && ls -la "$GITHUB_WORKSPACE/test/kernel"
        
